# Rest Client (VS Code Extension - HTTP Requests)
@server=http://localhost:3000
@createInvestmentId={{createInvestment.response.body.$.id}}

### Create an investment
# @name createInvestment
POST {{server}}/api/investments
Content-Type: application/json

{
  "name": "Tesouro Selic 2031",
  "amount": 18654
}

### Create an investment without name
POST {{server}}/api/investments
Content-Type: application/json

{
  "amount": 18654
}

### Read investments
GET {{server}}/api/investments

### Read an investment
GET {{server}}/api/investments/{{createInvestmentId}}

### Read an investment with invalid id
GET {{server}}/api/investments/not-a-valid-id

### Update an investment
PUT {{server}}/api/investments/{{createInvestmentId}}
Content-Type: application/json

{
  "name": "Tesouro Selic 2031",
  "amount": 37308
}

### Update an investment without name
PUT {{server}}/api/investments/{{createInvestmentId}}
Content-Type: application/json

{
  "amount": 37308
}

### Update an investment with invalid id
PUT {{server}}/api/investments/not-a-valid-id
Content-Type: application/json

{
  "name": "Tesouro Selic 2031",
  "amount": 37308
}

### Delete an investment
DELETE {{server}}/api/investments/{{createInvestmentId}}

### Delete an investment with invalid id
DELETE {{server}}/api/investments/not-a-valid-id

### Get an invalid route (404)
GET {{server}}/api/invalid-route
